### PR TITLE
Add unified macros as extracted file

### PR DESCRIPTION
**Pull request by sch3m4**

### CODE REVIEW

**Comment by gaelmuller** [comment]
Sorry about the delay ...

I am not sure I understand what you are trying to achieve here. Could you explain your goal ?

I don't think a new analysis of the vba file would result in anything interesting with current modules.

**Comment by sch3m4** [comment]
To be able to extract and get unified the main malware artifact.

**Comment by gaelmuller** [comment]
If your goal is to be able to download the unified macros, this should be a support file instead of an extracted file. 

I think the best is to provide this as configuration options. This is what has be done recently in the `cutthecrap`module:

```
        {
            'name': 'add_to_support_files',
            'type': 'bool',
            'default': False,
            'description': 'Adds the dropped files to support files (so that they can be downloaded).',
        },
        {
            'name': 'add_to_extracted_files',
            'type': 'bool',
            'default': True,
            'description': 'Adds the dropped files to extracted files (they will have their own analysis).',
        }
```

**Comment by gaelmuller** [comment]
Closed for inactivity, do not hesitate to reopen if needed

**Pull request closed without merging**
