### PR TITLE
Docker inception

### PR DESCRIPTION
**Pull request by lucebac**

### CODE REVIEW

**Comment by gaelmuller** [comment]
I am not sure I fully understand this.

Could you explain why changes to the modules would be necessary ? I would expect them to work as is inside or outside of docker.

**Comment by lucebac** [comment]
I had a look at the code and if I remember correctly, the changes are mainly caused by the fact that when we have the dockerized environment we cannot mount files from the one container into another container from inside the worker container (because we cannot determine the host path of the file which is required in that case). Thus, we implemented that the files are shovelled into a docker volume which is then mounted into the analyzer container because volumes are mounted by their name and not their path.

**Comment by lucebac** [comment]
The changes to the bash scripts and install files are in preparation of a planned feature from our side: currently, it is not possible to (forcefully) rebuild the docker containers for e.g. the exiftool or the url_preview module. But we think it would be an important feature to be able to once in a while rebuild the container from the web interface without having to remove and re-add the repository so that the containers are rebuild. Thus, we split the scripts into two parts: one sets up required system packages (usually just docker) and the other to build the container. Eventually, the latter can then be used to rebuild the container once the feature is implemented in the web interface.

**Comment by Augustin-FL** [comment]
Hi,

We have decided to use DinD instead of DooD, removing the need for modules rework (DinD handle volumes correctly...)

Also, the small additional functionalities (Decode UTF8 output from some modules, don't run exiftool on URLs, etc) in this PR have already been implemented.

I will close this PR. Feel free to reopen it if needed

**Pull request closed without merging**
